# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rrupp <rrupp@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/19 12:02:21 by rrupp             #+#    #+#              #
#    Updated: 2023/08/12 15:46:33 by rrupp            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := bullshit

CFLAGS := -Wall -Werror -Wextra -std=c++98 -g

CC := c++

OBJ_P := ./obj/

SRC :=	main.cpp		\
		AMateria.cpp	\
		Character.cpp	\
		Cure.cpp		\
		Ice.cpp			\
		MateriaSource.cpp

OBJ := $(SRC:%.cpp=$(OBJ_P)%.o)

$(OBJ_P)%.o:%.cpp
	mkdir -p obj
	$(CC) $(CFLAGS) -c $< -o $@

.SILENT:

.PHONY:
	all clean fclean re

all:$(NAME)

vpath %.cpp src

$(NAME): $(OBJ)
	$(CC) -o $(NAME) $(OBJ)
	echo "build message!"

clean:
	rm -f $(OBJ)
	rm -fd $(OBJ_P)
	echo "Deleted the o_files!"

fclean: clean
	rm -f $(NAME)
	echo "delete message!"

re: fclean all